using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Phymnary.SugarPot.RoslynComponents.Models;
using static AspNetCore.Boilerplate.Roslyn.Constants.GeneratorConstant;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace AspNetCore.Boilerplate.Roslyn.Components.Endpoint;

partial class EndpointGenerator
{
    private static class BuildSyntax
    {
        public static CompilationUnitSyntax GetCompilationUnitForEndpoint(
            HierarchyInfo hierarchyInfo,
            LocalDeclarationStatementSyntax mapRouteSyntax,
            ExpressionStatementSyntax? buildRouteSyntax
        )
        {
            var block = Block().AddStatements(mapRouteSyntax);

            if (buildRouteSyntax is not null)
                block = block.AddStatements(buildRouteSyntax);

            block = block.AddStatements(ReturnStatement(IdentifierName("builder")));

            TypeDeclarationSyntax typeDeclarationSyntax = (
                (ClassDeclarationSyntax)
                    hierarchyInfo
                        .Hierarchy[0]
                        .GetSyntax()
                        .AddModifiers(Token(SyntaxKind.PartialKeyword))
                        .AddBaseListTypes(
                            SimpleBaseType(IdentifierName($"global::{LibNamespaceApi}.IEndpoint"))
                        )
            ).AddMembers(
                MethodDeclaration(
                        IdentifierName("global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder"),
                        Identifier("ConfigureRouteBuilder")
                    )
                    .WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword)))
                    .WithParameterList(
                        ParameterList(
                            SingletonSeparatedList(
                                Parameter(Identifier("app"))
                                    .WithType(
                                        IdentifierName(
                                            "global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder"
                                        )
                                    )
                            )
                        )
                    )
                    .WithBody(block)
            );

            var hierarchySpan = hierarchyInfo.Hierarchy.AsSpan();
            foreach (var parentType in hierarchySpan.Slice(1))
                typeDeclarationSyntax = parentType
                    .GetSyntax()
                    .AddModifiers(Token(SyntaxKind.PartialKeyword))
                    .AddMembers(typeDeclarationSyntax);

            var syntaxTriviaList = TriviaList(
                Comment("// <auto-generated/>"),
                Trivia(PragmaWarningDirectiveTrivia(Token(SyntaxKind.DisableKeyword), true)),
                Trivia(NullableDirectiveTrivia(Token(SyntaxKind.EnableKeyword), true))
            );

            if (hierarchyInfo.Namespace is "")
                return CompilationUnit()
                    .AddMembers(typeDeclarationSyntax.WithLeadingTrivia(syntaxTriviaList))
                    .NormalizeWhitespace();

            return CompilationUnit()
                .AddMembers(
                    NamespaceDeclaration(IdentifierName(hierarchyInfo.Namespace))
                        .AddMembers(typeDeclarationSyntax)
                        .WithLeadingTrivia(syntaxTriviaList)
                )
                .NormalizeWhitespace();
        }

        private static readonly SyntaxToken[] PublicStatic =
        {
            Token(SyntaxKind.PublicKeyword),
            Token(SyntaxKind.StaticKeyword),
        };

        private static readonly SyntaxToken[] Public = { Token(SyntaxKind.PublicKeyword) };

        public static CompilationUnitSyntax GetCompilationUnitForController(
            HierarchyInfo hierarchyInfo,
            bool isStatic,
            ImmutableArray<ExpressionStatementSyntax> mapNonConstructExpression,
            ImmutableArray<ExpressionStatementSyntax> mapHasConstructExpression
        )
        {
            var method = MethodDeclaration(
                    PredefinedType(Token(SyntaxKind.VoidKeyword)),
                    Identifier("MapEndpoints")
                )
                .AddModifiers(isStatic ? PublicStatic : Public)
                .WithParameterList(
                    ParameterList(
                        SingletonSeparatedList(
                            Parameter(Identifier("app"))
                                .WithType(
                                    IdentifierName(
                                        "global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder"
                                    )
                                )
                        )
                    )
                )
                .AddBodyStatements(mapNonConstructExpression.ToArray<StatementSyntax>());

            if (mapHasConstructExpression.Length > 0)
            {
                method = method
                    .AddBodyStatements(
                        LocalDeclarationStatement(
                                VariableDeclaration(
                                        AliasQualifiedName(
                                            IdentifierName(Token(SyntaxKind.GlobalKeyword)),
                                            IdentifierName(
                                                "Microsoft.Extensions.DependencyInjection.IServiceScope"
                                            )
                                        )
                                    )
                                    .WithVariables(
                                        SingletonSeparatedList(
                                            VariableDeclarator(Identifier("scope"))
                                                .WithInitializer(
                                                    EqualsValueClause(
                                                        InvocationExpression(
                                                                MemberAccessExpression(
                                                                    SyntaxKind.SimpleMemberAccessExpression,
                                                                    AliasQualifiedName(
                                                                        IdentifierName(
                                                                            Token(
                                                                                SyntaxKind.GlobalKeyword
                                                                            )
                                                                        ),
                                                                        IdentifierName(
                                                                            "Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions"
                                                                        )
                                                                    ),
                                                                    IdentifierName("CreateScope")
                                                                )
                                                            )
                                                            .AddArgumentListArguments(
                                                                Argument(
                                                                    MemberAccessExpression(
                                                                        SyntaxKind.SimpleMemberAccessExpression,
                                                                        IdentifierName("app"),
                                                                        IdentifierName(
                                                                            "ServiceProvider"
                                                                        )
                                                                    )
                                                                )
                                                            )
                                                    )
                                                )
                                        )
                                    )
                            )
                            .WithUsingKeyword(Token(SyntaxKind.UsingKeyword)),
                        LocalDeclarationStatement(
                            VariableDeclaration(
                                    AliasQualifiedName(
                                        IdentifierName(Token(SyntaxKind.GlobalKeyword)),
                                        IdentifierName("System.IServiceProvider")
                                    )
                                )
                                .WithVariables(
                                    SingletonSeparatedList(
                                        VariableDeclarator(Identifier("serviceProvider"))
                                            .WithInitializer(
                                                EqualsValueClause(
                                                    MemberAccessExpression(
                                                        SyntaxKind.SimpleMemberAccessExpression,
                                                        IdentifierName("scope"),
                                                        IdentifierName("ServiceProvider")
                                                    )
                                                )
                                            )
                                    )
                                )
                        )
                    )
                    .AddBodyStatements(mapHasConstructExpression.ToArray<StatementSyntax>());
            }

            TypeDeclarationSyntax typeDeclarationSyntax = (
                (ClassDeclarationSyntax)
                    hierarchyInfo
                        .Hierarchy[0]
                        .GetSyntax()
                        .AddModifiers(Token(SyntaxKind.PartialKeyword))
            ).AddMembers(method);

            var hierarchySpan = hierarchyInfo.Hierarchy.AsSpan();
            foreach (var parentType in hierarchySpan.Slice(1))
                typeDeclarationSyntax = parentType
                    .GetSyntax()
                    .AddModifiers(Token(SyntaxKind.PartialKeyword))
                    .AddMembers(typeDeclarationSyntax);

            var syntaxTriviaList = TriviaList(
                Comment("// <auto-generated/>"),
                Trivia(PragmaWarningDirectiveTrivia(Token(SyntaxKind.DisableKeyword), true)),
                Trivia(NullableDirectiveTrivia(Token(SyntaxKind.EnableKeyword), true))
            );

            if (hierarchyInfo.Namespace is "")
                return CompilationUnit()
                    .AddMembers(typeDeclarationSyntax.WithLeadingTrivia(syntaxTriviaList))
                    .NormalizeWhitespace();

            return CompilationUnit()
                .AddMembers(
                    NamespaceDeclaration(IdentifierName(hierarchyInfo.Namespace))
                        .AddMembers(typeDeclarationSyntax)
                        .WithLeadingTrivia(syntaxTriviaList)
                )
                .NormalizeWhitespace();
        }
    }
}
