//using AspNetCore.Boilerplate.Api;
//using AspNetCore.Boilerplate.Roslyn.Components.Endpoint;
//using Microsoft.AspNetCore.Routing;
//using Microsoft.CodeAnalysis;
//using Microsoft.CodeAnalysis.CSharp;
//using Xunit;

//namespace AspNetCore.Boilerplate.Roslyn.Tests;

//public class ApiSchemaGeneratorTest
//{
//    private const string ClassText = """
//        using System;

//        namespace TestNamespace.SourceGenerator.GET
//        {
//            [global::AspNetCore.Boilerplate.Api.ApiSchema]
//            public partial class AppApiSchema
//            {
//            }

//            public static class ApiGroup
//            {
//                [global::AspNetCore.Boilerplate.Api.RoutePattern]
//                public static string GetRouteName<TEndpoint>(TEndpoint endpoint, string? prefix = null)
//                    where TEndpoint : class, global::AspNetCore.Boilerplate.Api.IEndpoint
//                {
//                    return "";
//                }

//                [global::AspNetCore.Boilerplate.Api.RouteBuilder]
//                public static void BuildRoute(Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
//                {
//                    builder.RequireAuthorization();
//                }
//            }
            
//            [global::AspNetCore.Boilerplate.Api.Endpoint]
//            public partial class PostDunking
//            {
//                public int HandleAsync() { return 1; }
//            }
            
//            [global::AspNetCore.Boilerplate.Api.Endpoint]
//            public partial class GetBaller
//            {
//                public GetBaller(IRouteProvider routeProvider)
//                {
                
//                }
            
//                private static string RoutePattern => routeProvider.Get(this);
            
//                public string HandleAsync() { return "LeBron"; }
//            }
//        }
//        """;

//    [Fact]
//    public void generate_endpoints()
//    {
//        var ct = TestContext.Current.CancellationToken;
//        var generator = new EndpointGenerator();

//        var driver = CSharpGeneratorDriver.Create(generator);

//        // We need to create a compilation with the required source code.
//        var compilation = CSharpCompilation.Create(
//            nameof(ApiSchemaGeneratorTest),
//            [CSharpSyntaxTree.ParseText(ClassText, cancellationToken: ct)],
//            [
//                // To support 'System.Attribute' inheritance, add reference to 'System.Private.CoreLib'.
//                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
//                MetadataReference.CreateFromFile(typeof(IEndpoint).Assembly.Location),
//                MetadataReference.CreateFromFile(typeof(EndpointAttribute).Assembly.Location),
//                MetadataReference.CreateFromFile(typeof(IEndpointRouteBuilder).Assembly.Location),
//            ]
//        );

//        var runResult = driver.RunGenerators(compilation, ct).GetRunResult();
//        var generatedDunkFileSyntax = runResult.GeneratedTrees.Single(t =>
//            t.FilePath.EndsWith("PostDunking.g.cs")
//        );
//        var generatedBallerFileSyntax = runResult.GeneratedTrees.Single(t =>
//            t.FilePath.EndsWith("GetBaller.g.cs")
//        );
//        var generatedControllerSyntax = runResult.GeneratedTrees.Single(t =>
//            t.FilePath.EndsWith("AppApiSchema.g.cs")
//        );

//        Assert.Equal(ExpectedDunkEndpointGenerated, generatedDunkFileSyntax.GetText(ct).ToString());
//        Assert.Equal(
//            ExpectedBallerEndpointGenerated,
//            generatedBallerFileSyntax.GetText(ct).ToString()
//        );
//        Assert.Equal(ExpectedControllerGenerated, generatedControllerSyntax.GetText(ct).ToString());
//    }

//    private const string ExpectedDunkEndpointGenerated = """
//        // <auto-generated/>
//        #pragma warning disable
//        #nullable enable
//        namespace TestNamespace.SourceGenerator.GET
//        {
//            partial class PostDunking : global::AspNetCore.Boilerplate.Api.IEndpoint
//            {
//                public global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder ConfigureRouteBuilder(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)
//                {
//                    var builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPost(app, global::TestNamespace.SourceGenerator.GET.ApiGroup.GetRouteName(this), HandleAsync);
//                    builder = global::TestNamespace.SourceGenerator.GET.ApiGroup.BuildRoute(builder);
//                    return builder;
//                }
//            }
//        }
//        """;

//    private const string ExpectedBallerEndpointGenerated = """
//        // <auto-generated/>
//        #pragma warning disable
//        #nullable enable
//        namespace TestNamespace.SourceGenerator.GET
//        {
//            partial class GetBaller : global::AspNetCore.Boilerplate.Api.IEndpoint
//            {
//                public global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder ConfigureRouteBuilder(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)
//                {
//                    var builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGet(app, global::TestNamespace.SourceGenerator.GET.ApiGroup.GetRouteName(this), HandleAsync);
//                    builder = global::TestNamespace.SourceGenerator.GET.ApiGroup.BuildRoute(builder);
//                    return builder;
//                }
//            }
//        }
//        """;

//    private const string ExpectedControllerGenerated = """
//        // <auto-generated/>
//        #pragma warning disable
//        #nullable enable
//        namespace TestNamespace.SourceGenerator.GET
//        {
//            partial class ApiSchema
//            {
//                public void MapEndpoints(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)
//                {
//                    global::AspNetCore.Boilerplate.Api.Extensions.EndpointRouteBuilderExtensions.MapEndpoint<global::TestNamespace.SourceGenerator.Connect.GET.PostDunking>(app);
//                }
//            }
//        }
//        """;
//}
