using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.Extensions.DependencyInjection;
using Phymnary.SugarPot.DependencyInjection;
using Phymnary.SugarPot.DependencyInjection.Roslyn.Components.AutoRegister;
using Xunit;

namespace Phymnary.SugarPot.Roslyn.Tests;

public sealed class ServiceGeneratorTest
{
    private const string LibNamespace = "global::Phymnary.SugarPot.DependencyInjection";

    private const string ServiceClassText = $$"""
        using System;
        using Microsoft.Extensions.DependencyInjection;
        using AspNetCore.Boilerplate;

        namespace TestNamespace
        {
            public interface IFooService {}

            [{{LibNamespace}}.Service({{LibNamespace}}.Lifetime.Scoped)]
            public class FooService : IFooService {}
        }
        """;

    private const string AutoRegisterClassText = $$"""
        using System;

        namespace TestNamespace 
        {
            [{{LibNamespace}}.Auto]
            internal partial class AutoRegisterClass {}
        }
        """;

    private const string Expected = """
        // <auto-generated/>
        #pragma warning disable
        #nullable enable
        namespace TestNamespace
        {
            partial class AutoRegisterClass : Phymnary.SugarPot.DependencyInjection.IAutoRegister
            {
                public void AddDependencies(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                {
                }
            }
        }
        """;

    [Fact]
    public void generate_auto_register_dependency_methods_for_partial_class()
    {
        var ct = TestContext.Current.CancellationToken;
        // Create an instance of the source generator.
        var generator = new AutoRegisterGenerator();

        // Source generators should be tested using 'GeneratorDriver'.
        var driver = CSharpGeneratorDriver.Create(generator);

        // We need to create a compilation with the required source code.
        var compilation = CSharpCompilation.Create(
            nameof(ServiceGeneratorTest),
            [
                CSharpSyntaxTree.ParseText(ServiceClassText, cancellationToken: ct),
                CSharpSyntaxTree.ParseText(AutoRegisterClassText, cancellationToken: ct),
            ],
            [
                // To support 'System.Attribute' inheritance, add reference to 'System.Private.CoreLib'.
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(AutoAttribute).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(IServiceCollection).Assembly.Location),
            ]
        );

        var runResult = driver.RunGenerators(compilation, ct).GetRunResult();
        var generatedFileSyntax = runResult
            .GeneratedTrees.Single(t => t.FilePath.EndsWith("AutoRegisterClass.g.cs"))
            .GetText(ct)
            .ToString();

        Assert.Equal(Expected, generatedFileSyntax, ignoreLineEndingDifferences: true);
    }
}
