using Microsoft.AspNetCore.Routing;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Phymnary.SugarPot.AspNetCore.Api;
using Phymnary.SugarPot.AspNetCore.Api.Roslyn.Components.Endpoint;
using Xunit;

namespace Phymnary.SugarPot.Roslyn.Tests;

public class EndpointGeneratorTest
{
    [Fact]
    public void generate_endpoints()
    {
        var ct = TestContext.Current.CancellationToken;
        var generator = new EndpointGenerator();

        var driver = CSharpGeneratorDriver.Create(generator);

        // We need to create a compilation with the required source code.
        var compilation = CSharpCompilation.Create(
            nameof(EndpointGeneratorTest),
            [CSharpSyntaxTree.ParseText(ClassText, cancellationToken: ct)],
            [
                // To support 'System.Attribute' inheritance, add reference to 'System.Private.CoreLib'.
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(IEndpoint).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(IEndpointRouteBuilder).Assembly.Location),
            ]
        );

        var runResult = driver.RunGenerators(compilation, ct).GetRunResult();
        var generatedPostUser = runResult
            .GeneratedTrees.Single(t => t.FilePath.EndsWith("PostUser.g.cs"))
            .GetText(ct)
            .ToString();
        var generatedGetUserFileSyntax = runResult
            .GeneratedTrees.Single(t => t.FilePath.EndsWith("GetUser.g.cs"))
            .GetText(ct)
            .ToString();
        var generatedControllerSyntax = runResult
            .GeneratedTrees.Single(t => t.FilePath.EndsWith("AppApiSchema.g.cs"))
            .GetText(ct)
            .ToString();

        Assert.Equal(ExpectedDunkEndpointGenerated, generatedPostUser);
        Assert.Equal(ExpectedGetUserEndpointGenerated, generatedGetUserFileSyntax);
        Assert.Equal(ExpectedControllerGenerated, generatedControllerSyntax);
    }

    private const string ClassText = """
        using System;

        namespace TestNamespace.SourceGenerator.GET
        {
            [global::Phymnary.SugarPot.AspNetCore.Api.ApiSchema]
            public partial class AppApiSchema
            {
            }

            public static class ApiGroup
            {
                [global::Phymnary.SugarPot.AspNetCore.Api.RoutePattern]
                public static string GetRouteName<TEndpoint>(TEndpoint endpoint, string? prefix = null)
                    where TEndpoint : class, global::Phymnary.SugarPot.AspNetCore.Api.IEndpoint
                {
                    return "";
                }

                [global::Phymnary.SugarPot.AspNetCore.Api.RouteBuilder]
                public static Microsoft.AspNetCore.Builder.RouteHandlerBuilder BuildRoute(Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder)
                {
                    builder.RequireAuthorization();
                    return builder;
                }
            }
            
            [global::Phymnary.SugarPot.AspNetCore.Api.Endpoint]
            public partial class PostUser
            {
                public int HandleAsync() { return 1; }
            }
            
            [global::Phymnary.SugarPot.AspNetCore.Api.Endpoint]
            public partial class GetUser
            {
                public GetUser(IRouteProvider routeProvider)
                {
                }
            
                private static string RoutePattern => routeProvider.Get(this);
            
                public string HandleAsync() { return "Foo"; }
            }
        }
        """;

    private const string ExpectedDunkEndpointGenerated = """
        // <auto-generated/>
        #pragma warning disable
        #nullable enable
        namespace TestNamespace.SourceGenerator.GET
        {
            /// <inheritdoc/>
            partial class PostUser : global::Phymnary.SugarPot.AspNetCore.Api.IEndpoint
            {
                public global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder ConfigureRouteBuilder(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)
                {
                    var builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPost(app, global::TestNamespace.SourceGenerator.GET.ApiGroup.GetRouteName(this), HandleAsync);
                    builder = global::TestNamespace.SourceGenerator.GET.ApiGroup.BuildRoute(builder);
                    return builder;
                }
            }
        }
        """;

    private const string ExpectedGetUserEndpointGenerated = """
        // <auto-generated/>
        #pragma warning disable
        #nullable enable
        namespace TestNamespace.SourceGenerator.GET
        {
            /// <inheritdoc/>
            partial class GetUser : global::Phymnary.SugarPot.AspNetCore.Api.IEndpoint
            {
                public global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder ConfigureRouteBuilder(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)
                {
                    var builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGet(app, RoutePattern, HandleAsync);
                    builder = global::TestNamespace.SourceGenerator.GET.ApiGroup.BuildRoute(builder);
                    return builder;
                }
            }
        }
        """;

    private const string ExpectedControllerGenerated = """
        // <auto-generated/>
        #pragma warning disable
        #nullable enable
        namespace TestNamespace.SourceGenerator.GET
        {
            /// <inheritdoc/>
            partial class AppApiSchema
            {
                public void MapEndpoints(global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)
                {
                    global::Phymnary.SugarPot.AspNetCore.Api.Extensions.EndpointRouteBuilderExtensions.MapEndpoint<global::TestNamespace.SourceGenerator.GET.PostUser>(app);
                    using global::Microsoft.Extensions.DependencyInjection.IServiceScope scope = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateScope(app.ServiceProvider);
                    global::System.IServiceProvider serviceProvider = scope.ServiceProvider;
                    global::Phymnary.SugarPot.AspNetCore.Api.Extensions.EndpointRouteBuilderExtensions.MapEndpoint<global::TestNamespace.SourceGenerator.GET.GetUser>(app, serviceProvider);
                }
            }
        }
        """;
}
